Print out all simulation failures when there are multiple failures
Previously, `copilot-verifier` would simply print out
`Simulation aborted for multiple reasons` when there were multiple failures,
which wasn't terribly helpful. After this patch, we get something more
informative:

```
verify-examples: user error (Simulation aborted for multiple reasons.
Simulation aborted!
Abort due to assertion failure:
  results/wcv/wcv.c:21:202: error: in well_clear_violation_guard
  Failed to load function handle
  Details:
    No implementation or override found for pointer: "llvm.fabs.f64"
Simulation aborted!
Abort due to assertion failure:
  results/wcv/wcv.c:21:4576: error: in well_clear_violation_guard
  Failed to load function handle
  Details:
    No implementation or override found for pointer: "llvm.fabs.f64")
```

It's a tad verbose, but we can improve the error-reporting story later.
See #12.